"""phase3_audit_versioning

Revision ID: 9f4c6b2ef919
Revises: db3b26e17a59
Create Date: 2025-11-13 22:26:33.214047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f4c6b2ef919'
down_revision: Union[str, Sequence[str], None] = 'db3b26e17a59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extraction_backup',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('backup_timestamp', sa.DateTime(), nullable=True),
    sa.Column('backup_type', sa.Enum('FULL', 'INCREMENTAL', name='backuptype'), nullable=False),
    sa.Column('records_count', sa.Integer(), nullable=False),
    sa.Column('backup_file_path', sa.String(length=1024), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('compression', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'FAILED', name='backupstatus'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_backup_backup_timestamp'), 'extraction_backup', ['backup_timestamp'], unique=False)
    op.create_index(op.f('ix_extraction_backup_status'), 'extraction_backup', ['status'], unique=False)
    op.create_table('extraction_metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('structure_score', sa.Float(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('superseded_by_id', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['extraction_metadata.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash', 'version', name='uq_file_hash_version')
    )
    op.create_index(op.f('ix_extraction_metadata_file_hash'), 'extraction_metadata', ['file_hash'], unique=False)
    op.create_index(op.f('ix_extraction_metadata_is_active'), 'extraction_metadata', ['is_active'], unique=False)
    op.create_index(op.f('ix_extraction_metadata_language'), 'extraction_metadata', ['language'], unique=False)
    op.create_index(op.f('ix_extraction_metadata_mime_type'), 'extraction_metadata', ['mime_type'], unique=False)
    op.create_table('duplication_audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_metadata_id', sa.Integer(), nullable=False),
    sa.Column('duplicate_file_path', sa.String(length=1024), nullable=False),
    sa.Column('duplicate_file_hash', sa.String(length=64), nullable=False),
    sa.Column('detection_timestamp', sa.DateTime(), nullable=True),
    sa.Column('action_taken', sa.Enum('SKIPPED', 'REPLACED', 'VERSIONED', 'NOTIFIED', name='duplicationauditlogaction'), nullable=False),
    sa.Column('user_notified', sa.Boolean(), nullable=True),
    sa.Column('metadata_diff', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['original_metadata_id'], ['extraction_metadata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_duplication_audit_log_action_taken'), 'duplication_audit_log', ['action_taken'], unique=False)
    op.create_index(op.f('ix_duplication_audit_log_detection_timestamp'), 'duplication_audit_log', ['detection_timestamp'], unique=False)
    op.create_index(op.f('ix_duplication_audit_log_duplicate_file_hash'), 'duplication_audit_log', ['duplicate_file_hash'], unique=False)
    op.create_index(op.f('ix_duplication_audit_log_original_metadata_id'), 'duplication_audit_log', ['original_metadata_id'], unique=False)
    op.create_table('extraction_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('metadata_id', sa.Integer(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('extraction_engine', sa.String(length=100), nullable=False),
    sa.Column('text_length', sa.Integer(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['metadata_id'], ['extraction_metadata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_results_metadata_id'), 'extraction_results', ['metadata_id'], unique=False)
    op.drop_index(op.f('idx_collection_name'), table_name='collection_index_configs')
    op.drop_index(op.f('idx_enabled_for_drafts'), table_name='collection_index_configs')
    op.create_index(op.f('ix_collection_index_configs_collection_name'), 'collection_index_configs', ['collection_name'], unique=True)
    op.create_index(op.f('ix_collection_index_configs_enabled_for_drafts'), 'collection_index_configs', ['enabled_for_drafts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collection_index_configs_enabled_for_drafts'), table_name='collection_index_configs')
    op.drop_index(op.f('ix_collection_index_configs_collection_name'), table_name='collection_index_configs')
    op.create_index(op.f('idx_enabled_for_drafts'), 'collection_index_configs', ['enabled_for_drafts'], unique=False)
    op.create_index(op.f('idx_collection_name'), 'collection_index_configs', ['collection_name'], unique=False)
    op.drop_index(op.f('ix_extraction_results_metadata_id'), table_name='extraction_results')
    op.drop_table('extraction_results')
    op.drop_index(op.f('ix_duplication_audit_log_original_metadata_id'), table_name='duplication_audit_log')
    op.drop_index(op.f('ix_duplication_audit_log_duplicate_file_hash'), table_name='duplication_audit_log')
    op.drop_index(op.f('ix_duplication_audit_log_detection_timestamp'), table_name='duplication_audit_log')
    op.drop_index(op.f('ix_duplication_audit_log_action_taken'), table_name='duplication_audit_log')
    op.drop_table('duplication_audit_log')
    op.drop_index(op.f('ix_extraction_metadata_mime_type'), table_name='extraction_metadata')
    op.drop_index(op.f('ix_extraction_metadata_language'), table_name='extraction_metadata')
    op.drop_index(op.f('ix_extraction_metadata_is_active'), table_name='extraction_metadata')
    op.drop_index(op.f('ix_extraction_metadata_file_hash'), table_name='extraction_metadata')
    op.drop_table('extraction_metadata')
    op.drop_index(op.f('ix_extraction_backup_status'), table_name='extraction_backup')
    op.drop_index(op.f('ix_extraction_backup_backup_timestamp'), table_name='extraction_backup')
    op.drop_table('extraction_backup')
    # ### end Alembic commands ###
